name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there, Thank you for reporting this. We will make sure to respond as fast as possible. It looks like this may be your first contribution to the BBjGridExWidget project. Did you check if someone else reported a similar issue? you can browse the [issues list in here](https://github.com/BBj-Plugins/BBjGridExWidget/issues)'
        pr-message: 'Hi there,  It looks like this may be your first contribution to the BBjGridExWidget project. Thank you, One of the project maintainers will review your PR as soon as possible.'
